import os
import argparse

parser = argparse.ArgumentParser(description='SNN training')
parser.add_argument('--seed', default=None, type=int)
parser.add_argument('--dataset', default='EuroSAT', type=str)
parser.add_argument('--train_batch_size', default=32, type=int)
parser.add_argument('--test_batch_size', default=32, type=int)
parser.add_argument('--lr', default=0.05, type=float)
parser.add_argument('--lr_decay_phase', default=10, type=int)
parser.add_argument('--lr_decay_ratio', default=0.8, type=float)
parser.add_argument('--width_lr', default=0.001, type=float)
parser.add_argument('--bn_type', default='tdbn', type=str)
parser.add_argument('--bias', default=False, action='store_true')
parser.add_argument('--wd', default=0, type=float)
parser.add_argument('--num_epoch', default=60, type=int)
parser.add_argument('--num_workers', default=10, type=int)
parser.add_argument('--optim', default='SGDM', type=str)
parser.add_argument('--act', default='mns_sig', type=str)
parser.add_argument('--alpha', default=0.2, type=float)
# parser.add_argument('--alpha', default=5, type=float)

parser.add_argument('--plane_alpha', default=0.02, type=float)
parser.add_argument('--intra_plane_iters', default=2, type=int)
parser.add_argument('--local_iters', default=2, type=int)

parser.add_argument('--granularity', default='layer', type=str)
parser.add_argument('--decay', default=0.5, type=float)
parser.add_argument('--thresh', default=1.0, type=float)
parser.add_argument('--p', default=0.2, type=float)
# parser.add_argument('--p', default=0.1, type=float)
parser.add_argument('--gamma', default=1.0, type=float)
parser.add_argument('--train_decay', default=False, action='store_true')
parser.add_argument('--train_thresh', default=False, action='store_true')
parser.add_argument('--device', default='cuda:0', type=str)
parser.add_argument('--T', default=3, type=int, help='num of time steps')
parser.add_argument('--log_interval', default='20', type=int)

parser.add_argument('--means', default=1.0, type=float, metavar='N',
                    help='make all the potential increment around the means')
parser.add_argument('--lamb', default=1e-3, type=float, metavar='N', help='adjust the norm factor to avoid outlier')
parser.add_argument('--train_width', default=True, action='store_true')
parser.add_argument('--ns_milestone', default=[0, 0.2, 0.4, 0.6, 0.8, 0.95], type=float, nargs='*', )

args = parser.parse_args()

parser2 = argparse.ArgumentParser(description='SNN training v2')
parser2.add_argument('--seed', default=None, type=int)
parser2.add_argument('--dataset', default='EuroSAT', type=str)
parser2.add_argument('--train_batch_size', default=32, type=int)
parser2.add_argument('--test_batch_size', default=32, type=int)
parser2.add_argument('--lr', default=0.05, type=float)
parser2.add_argument('--width_lr', default=0.001, type=float)
parser2.add_argument('--lr_decay_phase', default=10, type=int)
parser2.add_argument('--lr_decay_ratio', default=0.8, type=float)
parser2.add_argument('--bn_type', default='tdbn', type=str)
parser2.add_argument('--bias', default=False, action='store_true')
parser2.add_argument('--wd', default=0, type=float)
parser2.add_argument('--num_epoch', default=60, type=int)
parser2.add_argument('--num_workers', default=10, type=int)
parser2.add_argument('--optim', default='SGDM', type=str)
parser2.add_argument('--act', default='mns_sig', type=str)
parser2.add_argument('--alpha', default=0.2, type=float)
# parser.add_argument('--alpha', default=5, type=float)

parser2.add_argument('--plane_alpha', default=0.02, type=float)
parser2.add_argument('--intra_plane_iters', default=2, type=int)
parser2.add_argument('--local_iters', default=2, type=int)

parser2.add_argument('--granularity', default='layer', type=str)
parser2.add_argument('--decay', default=0.5, type=float)
parser2.add_argument('--thresh', default=1.0, type=float)
parser2.add_argument('--p', default=0.2, type=float)
# parser.add_argument('--p', default=0.1, type=float)
parser2.add_argument('--gamma', default=1.0, type=float)
parser2.add_argument('--train_decay', default=False, action='store_true')
parser2.add_argument('--train_thresh', default=False, action='store_true')
parser2.add_argument('--device', default='cuda:0', type=str)
parser2.add_argument('--T', default=3, type=int, help='num of time steps')
parser2.add_argument('--log_interval', default='20', type=int)

parser2.add_argument('--means', default=1.0, type=float, metavar='N',
                    help='make all the potential increment around the means')
parser2.add_argument('--lamb', default=1e-3, type=float, metavar='N', help='adjust the norm factor to avoid outlier')
parser2.add_argument('--train_width', default=True, action='store_true')
parser2.add_argument('--ns_milestone', default=[0, 0.2, 0.4, 0.6, 0.8, 0.95], type=float, nargs='*', )

args2 = parser2.parse_args()

parser3 = argparse.ArgumentParser(description='SNN training v3')
parser3.add_argument('--seed', default=None, type=int)
parser3.add_argument('--dataset', default='EuroSAT', type=str)
parser3.add_argument('--train_batch_size', default=32, type=int)
parser3.add_argument('--test_batch_size', default=32, type=int)
parser3.add_argument('--lr', default=0.05, type=float)
parser3.add_argument('--lr_decay_phase', default=10, type=int)
parser3.add_argument('--lr_decay_ratio', default=0.8, type=float)
parser3.add_argument('--width_lr', default=0.001, type=float)
parser3.add_argument('--bn_type', default='tdbn', type=str)
parser3.add_argument('--bias', default=False, action='store_true')
parser3.add_argument('--wd', default=0, type=float)
parser3.add_argument('--num_epoch', default=60, type=int)
parser3.add_argument('--num_workers', default=10, type=int)
parser3.add_argument('--optim', default='SGDM', type=str)
parser3.add_argument('--act', default='mns_sig', type=str)
parser3.add_argument('--alpha', default=0.2, type=float)
# parser.add_argument('--alpha', default=5, type=float)

parser3.add_argument('--plane_alpha', default=0.2, type=float)
parser3.add_argument('--intra_plane_iters', default=2, type=int)
parser3.add_argument('--local_iters', default=2, type=int)

parser3.add_argument('--granularity', default='layer', type=str)
parser3.add_argument('--decay', default=0.5, type=float)
parser3.add_argument('--thresh', default=1.0, type=float)
parser3.add_argument('--p', default=0.2, type=float)
# parser.add_argument('--p', default=0.1, type=float)
parser3.add_argument('--gamma', default=1.0, type=float)
parser3.add_argument('--train_decay', default=False, action='store_true')
parser3.add_argument('--train_thresh', default=False, action='store_true')
parser3.add_argument('--device', default='cuda:0', type=str)
parser3.add_argument('--T', default=3, type=int, help='num of time steps')
parser3.add_argument('--log_interval', default='20', type=int)

parser3.add_argument('--means', default=1.0, type=float, metavar='N',
                    help='make all the potential increment around the means')
parser3.add_argument('--lamb', default=1e-3, type=float, metavar='N', help='adjust the norm factor to avoid outlier')
parser3.add_argument('--train_width', default=True, action='store_true')
parser3.add_argument('--ns_milestone', default=[0, 0.2, 0.4, 0.6, 0.8, 0.95], type=float, nargs='*', )

args3 = parser3.parse_args()

parser4 = argparse.ArgumentParser(description='SNN training v4')
parser4.add_argument('--seed', default=None, type=int)
parser4.add_argument('--dataset', default='EuroSAT', type=str)
parser4.add_argument('--train_batch_size', default=32, type=int)
parser4.add_argument('--test_batch_size', default=32, type=int)
parser4.add_argument('--lr', default=0.05, type=float)
parser4.add_argument('--lr_decay_phase', default=5, type=int)
parser4.add_argument('--lr_decay_ratio', default=0.9, type=float)
parser4.add_argument('--width_lr', default=0.0008, type=float)
parser4.add_argument('--bn_type', default='tdbn', type=str)
parser4.add_argument('--bias', default=False, action='store_true')
parser4.add_argument('--wd', default=0, type=float)
parser4.add_argument('--num_epoch', default=60, type=int)
parser4.add_argument('--num_workers', default=5, type=int)
parser4.add_argument('--optim', default='SGDM', type=str)
parser4.add_argument('--act', default='mns_sig', type=str)
parser4.add_argument('--alpha', default=0.2, type=float)
# parser.add_argument('--alpha', default=5, type=float)

parser4.add_argument('--plane_alpha', default=0.2, type=float)
parser4.add_argument('--intra_plane_iters', default=2, type=int)
parser4.add_argument('--local_iters', default=2, type=int)

parser4.add_argument('--granularity', default='layer', type=str)
parser4.add_argument('--decay', default=0.5, type=float)
parser4.add_argument('--thresh', default=1.0, type=float)
parser4.add_argument('--p', default=0.2, type=float)
# parser.add_argument('--p', default=0.1, type=float)
parser4.add_argument('--gamma', default=1.0, type=float)
parser4.add_argument('--train_decay', default=False, action='store_true')
parser4.add_argument('--train_thresh', default=False, action='store_true')
parser4.add_argument('--device', default='cuda:0', type=str)
parser4.add_argument('--T', default=3, type=int, help='num of time steps')
parser4.add_argument('--log_interval', default='20', type=int)

parser4.add_argument('--means', default=1.0, type=float, metavar='N',
                    help='make all the potential increment around the means')
parser4.add_argument('--lamb', default=1e-3, type=float, metavar='N', help='adjust the norm factor to avoid outlier')
parser4.add_argument('--train_width', default=True, action='store_true')
parser4.add_argument('--ns_milestone', default=[0, 0.2, 0.4, 0.6, 0.8, 0.95], type=float, nargs='*', )

args4 = parser4.parse_args()
